name: Sync to Hugging Face

on:
  push:
    branches: [ "main" ]
  # Cho phép kích hoạt thủ công từ giao diện Actions của GitHub
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Đồng bộ toàn bộ repository sang Hugging Face Space
          git push --force https://nguyenho17:$HF_TOKEN@huggingface.co/spaces/nguyenho17/ChatBotLuatHonNhan main
